### PR TITLE
Heif

### PR DESCRIPTION
**Pull request by aurelienpierre**

### CODE REVIEW

**Comment by cryptomilk** [comment]
I've fixed the switch, as it missed a break. However I don't get a picture out of it.

I used 

```heif-convert in.heif out.png```

**Comment by aurelienpierre** [comment]
Hmm, this is what I get 
[DSCF6202_02.zip](https://github.com/cryptomilk/darktable/files/3833589/DSCF6202_02.zip)

I open it with Gimp (there is a plugin for HEIF).

**Comment by cryptomilk** [comment]
I have the 8bit mode working, but 16bit still doesn't work.

**Comment by 1div0** [comment]
I had a success with the test of your code. I would recommend only few small corrections. Format itself is called HEIF, but file extension is .heic! Do not ask me why.

Next, with regard to the higher depth, x265 used by libheif currently supports 8, 10 and 12 bits per channel. I could focus on adding RExt 16 bpc, as I know that code while contributing to the project two years ago. So the bit depth option should be added accordingly.

Thank you so much.

**Comment by cryptomilk** [comment]
This is far away from being useable. I will look into it again after I finished AVIF support and libheif has the cmake PR merged. Also 16bit export segfaults.

Also note that you probably will get heif support only if you compile it yourself. HEIF is a patent minefield and no Linux distribution will ship it.

**Comment by 1div0** [comment]
€ rpm -qi libheif
Name        : libheif
Version     : 1.6.0
Release     : 1.fc31
Architecture: x86_64
Install Date: So  7. december 2019, 18:00:30 CET
Group       : Unspecified
Size        : 780942
License     : LGPLv3+ and MIT
Signature   : (none)
Source RPM  : libheif-1.6.0-1.fc31.src.rpm
Build Date  : So  7. december 2019, 17:59:31 CET
Build Host  : pascal
URL         : https://github.com/strukturag/libheif
Summary     : HEIF file format decoder and encoder
Description :
HEIF is a image format using HEVC image coding for the best compression ratios.
libheif uses libde265 for the actual image decoding and x265 for encoding.
Alternative codecs for, e.g., AVC and JPEG can be provided as plugins.

**Comment by 1div0** [comment]
https://packages.ubuntu.com/source/bionic/libheif

**Comment by 1div0** [comment]
https://svnweb.freebsd.org/ports/head/graphics/libheif/

**Comment by cryptomilk** [comment]
Oh, wow. Fedora doesn't package x264 but has libde265. Very strange.

**Comment by 1div0** [comment]
This is in RPM Fusion.

**Comment by cryptomilk** [comment]
Well, but darktable built in Fedora will not use libheif from RPM Fusion.

**Comment by cryptomilk** [comment]
What do you need heic for, iphone pictures?

**Comment by 1div0** [comment]
Just for curiosity, Krita built on Fedora detects if the libheif is installed and provides support.

**Comment by 1div0** [comment]
> What do you need heic for, iphone pictures?

To save storage space and bandwidth. For instance. Android 10 supports HEIF as well. 

JPEG is obsolete.

**Comment by cryptomilk** [comment]
I guess Android 10 also support AVIF or will soon, as Google is part of AOMedia.

**Comment by 1div0** [comment]
Searching AVIF through recent Android source code gives exactly zero results. It is not considered support. DOA

**Comment by cryptomilk** [comment]
https://github.com/cryptomilk/darktable/tree/master-heif <<< rewrite from scratch. Closing :-)

**Pull request closed without merging**
